# Generated by Django 6.0 on 2026-01-12 00:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheme",
                    models.CharField(
                        help_text="The protocol scheme of the URL, such as 'http' or 'https'.",
                        max_length=10,
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        help_text="The host or domain name of the URL, e.g., 'example.com'.",
                        max_length=255,
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text="The path component of the URL, e.g., '/api/v1/users'.",
                        max_length=2048,
                    ),
                ),
                (
                    "query",
                    models.TextField(
                        blank=True,
                        help_text="The query string of the URL, e.g., 'key1=value1&key2=value2'. Leave blank if none.",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        help_text="The HTTP method used in the request, e.g., 'GET', 'POST', 'PUT', 'DELETE'.",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="The IP address of the client that accessed the URL."
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="The user agent string from the HTTP request headers.",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="The username of the authenticated user, copied for logging purposes.",
                        max_length=150,
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        help_text="The timestamp when the request started processing."
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The timestamp when the response was sent.",
                        null=True,
                    ),
                ),
                (
                    "status_code",
                    models.IntegerField(
                        help_text="The HTTP status code of the response (e.g., 200, 404)."
                    ),
                ),
                (
                    "error",
                    models.TextField(
                        blank=True,
                        help_text="The response body content if an error occurred (status >= 400).",
                    ),
                ),
                (
                    "request_size",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The size of the request body in bytes.",
                    ),
                ),
                (
                    "response_size",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The size of the response body in bytes.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time when this record was first created.",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="The authenticated user making the request, if any.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Request",
                "verbose_name_plural": "Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
