# Generated by Django 6.0 on 2026-04-08 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("numenor_monitor", "0002_rename_ip_address_request_remote_addr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="request",
            name="remote_addr",
            field=models.GenericIPAddressField(
                help_text="The REMOTE_ADDR of the request — the direct TCP connection IP (proxy or client)."
            ),
        ),
    ]
